export default [
    {
        id: '00000006',
        perfundimtarja: 'dielli',
        a: 'yll',
        a1: 'hapesire',
        a2: 'vip',
        a3: 'nxehtesi',
        a4: 'berthame',
        b: 'sistem',
        b1: 'i arsimit',
        b2: 'organizim',
        b3: 'mbrojtes',
        b4: 'imunitar',
        c: 'syze',
        c1: 'sy',
        c2: 'aksesore',
        c3: 'mbrojtje',
        c4: 'thjerra',
        d: 'drite',
        d1: 'poç',
        d2: 'ndriçim',
        d3: 'vakum',
        d4: 'foton',
    },{
        id: '00000005',
        perfundimtarja: 'dielli',
        a: 'yll',
        a1: 'hapesire',
        a2: 'vip',
        a3: 'nxehtesi',
        a4: 'berthame',
        b: 'sistem',
        b1: 'i arsimit',
        b2: 'organizim',
        b3: 'mbrojtes',
        b4: 'imunitar',
        c: 'syze',
        c1: 'sy',
        c2: 'aksesore',
        c3: 'mbrojtje',
        c4: 'thjerra',
        d: 'drite',
        d1: 'poç',
        d2: 'ndriçim',
        d3: 'vakum',
        d4: 'foton',
    },{
        id: '00000004',
        perfundimtarja: 'dielli',
        a: 'yll',
        a1: 'hapesire',
        a2: 'vip',
        a3: 'nxehtesi',
        a4: 'berthame',
        b: 'sistem',
        b1: 'i arsimit',
        b2: 'organizim',
        b3: 'mbrojtes',
        b4: 'imunitar',
        c: 'syze',
        c1: 'sy',
        c2: 'aksesore',
        c3: 'mbrojtje',
        c4: 'thjerra',
        d: 'drite',
        d1: 'poç',
        d2: 'ndriçim',
        d3: 'vakum',
        d4: 'foton',
    },{
        id: '00000003',
        perfundimtarja: 'dielli',
        a: 'yll',
        a1: 'hapesire',
        a2: 'vip',
        a3: 'nxehtesi',
        a4: 'berthame',
        b: 'sistem',
        b1: 'i arsimit',
        b2: 'organizim',
        b3: 'mbrojtes',
        b4: 'imunitar',
        c: 'syze',
        c1: 'sy',
        c2: 'aksesore',
        c3: 'mbrojtje',
        c4: 'thjerra',
        d: 'drite',
        d1: 'poç',
        d2: 'ndriçim',
        d3: 'vakum',
        d4: 'foton',
    },{
        id: '00000002',
        perfundimtarja: 'dielli',
        a: 'yll',
        a1: 'hapesire',
        a2: 'vip',
        a3: 'nxehtesi',
        a4: 'berthame',
        b: 'sistem',
        b1: 'i arsimit',
        b2: 'organizim',
        b3: 'mbrojtes',
        b4: 'imunitar',
        c: 'syze',
        c1: 'sy',
        c2: 'aksesore',
        c3: 'mbrojtje',
        c4: 'thjerra',
        d: 'drite',
        d1: 'poç',
        d2: 'ndriçim',
        d3: 'vakum',
        d4: 'foton',
    },{
        id: '00000001',
        perfundimtarja: 'dielli',
        a: 'yll',
        a1: 'hapesire',
        a2: 'vip',
        a3: 'nxehtesi',
        a4: 'berthame',
        b: 'sistem',
        b1: 'i arsimit',
        b2: 'organizim',
        b3: 'mbrojtes',
        b4: 'imunitar',
        c: 'syze',
        c1: 'sy',
        c2: 'aksesore',
        c3: 'mbrojtje',
        c4: 'thjerra',
        d: 'drite',
        d1: 'poç',
        d2: 'ndriçim',
        d3: 'vakum',
        d4: 'foton',
    },
];